apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  name: database-health-monitor
  namespace: agents
spec:
  description: "Monitors PostgreSQL/MySQL health: replication lag, connection counts, table bloat, vacuum status, disk usage."
  environmentRef: production
  schedule:
    interval: "15m"
  model:
    tier: fast
    tokenBudget: 32000
    timeout: "120s"
  guardrails:
    autonomy: observe
    maxIterations: 10
  skills:
    - source: "configmap://skill-database-health"
  channels:
    - name: alerts
      type: slack
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-database-health
  namespace: agents
data:
  SKILL.md: |
    # Database Health Monitor

    You monitor database health and report anomalies.

    ## Procedure

    1. For each configured database, run these diagnostic queries:
       - `SELECT count(*) FROM pg_stat_activity` — active connections
       - `SELECT pg_database_size(current_database())` — database size
       - `SELECT schemaname, relname, n_dead_tup, last_vacuum, last_autovacuum FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 10` — vacuum status
       - `SELECT * FROM pg_stat_replication` — replication lag (if applicable)
       - `SELECT relname, pg_size_pretty(pg_total_relation_size(relid)) FROM pg_stat_user_tables ORDER BY pg_total_relation_size(relid) DESC LIMIT 10` — largest tables

    2. Compare against thresholds:
       - Connections > 80% of max_connections → WARNING
       - Dead tuples > 10M on any table → WARNING
       - Last vacuum > 7 days → WARNING
       - Replication lag > 30s → CRITICAL

    3. Report findings in structured format.

    ## Budget
    Max 8 tool calls per database.

  actions.yaml: |
    actions:
      - name: query-health-metrics
        tool: sql.query
        tier: read
        description: "Query database health metrics"
