apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  name: server-health-monitor
  namespace: agents
spec:
  description: >
    Monitors server health across the estate via SSH (through Headscale mesh).
    Checks disk usage, memory, CPU load, service status, security updates,
    and certificate expiry.
  environmentRef: enterprise-servers
  schedule:
    interval: "15m"
  model:
    tier: fast
    tokenBudget: 32000
    timeout: "120s"
  guardrails:
    autonomy: observe
    maxIterations: 12
  skills:
    - source: "configmap://skill-server-health"
  channels:
    - name: alerts
      type: slack
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-server-health
  namespace: agents
data:
  SKILL.md: |
    # Server Health Monitor

    You monitor server health across the estate via SSH. All servers are
    reachable through the Headscale mesh VPN — use their Tailscale hostnames.

    ## Procedure

    For each configured SSH host:

    1. **Disk usage**: `df -h | grep -E '^/dev'`
       - WARNING if any mount > 80%
       - CRITICAL if any mount > 90%

    2. **Memory**: `free -m | head -3`
       - WARNING if available < 20% of total

    3. **CPU load**: `uptime`
       - WARNING if 5-min load > number of CPUs

    4. **Key services**: `systemctl is-active <service>` for each expected service
       - CRITICAL if any expected service is not active

    5. **Security updates**: `apt list --upgradable 2>/dev/null | wc -l` or
       `yum check-update 2>/dev/null | tail -n +3 | wc -l`
       - WARNING if > 10 pending security updates

    6. **Certificate expiry**: `openssl s_client -connect localhost:443 < /dev/null 2>/dev/null | openssl x509 -noout -enddate`
       - WARNING if expiry < 30 days
       - CRITICAL if expiry < 7 days

    7. **Uptime and reboot**: `uptime -s` and check if reboot is pending
       (`[ -f /var/run/reboot-required ]`)

    ## Reporting

    Produce a structured report grouped by severity:
    - CRITICAL findings first
    - WARNING findings next
    - All-clear summary for healthy servers

    ## Budget
    Max 6 SSH commands per server. Max 3 servers per run.

  actions.yaml: |
    actions:
      - name: check-server-health
        tool: ssh.exec
        tier: read
        description: "Run health check commands on managed servers"
