apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  name: query-performance-auditor
  namespace: agents
spec:
  description: "Audits query performance using pg_stat_statements. Identifies slow queries, missing indexes, and sequential scans."
  environmentRef: production
  schedule:
    cron: "0 3 * * *"  # Daily at 3 AM
  model:
    tier: standard
    tokenBudget: 64000
    timeout: "180s"
  guardrails:
    autonomy: observe
    maxIterations: 12
  skills:
    - source: "configmap://skill-query-performance"
  channels:
    - name: alerts
      type: slack
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-query-performance
  namespace: agents
data:
  SKILL.md: |
    # Query Performance Auditor

    You analyse database query performance and recommend optimisations.

    ## Procedure

    1. Query performance data:
       - `SELECT query, calls, mean_exec_time, total_exec_time, rows FROM pg_stat_statements ORDER BY mean_exec_time DESC LIMIT 20` — slowest queries
       - `SELECT schemaname, relname, seq_scan, seq_tup_read, idx_scan, idx_tup_fetch FROM pg_stat_user_tables WHERE seq_scan > 1000 ORDER BY seq_scan DESC LIMIT 10` — tables with high sequential scans
       - `SELECT relname, indexrelname, idx_scan FROM pg_stat_user_indexes WHERE idx_scan = 0 ORDER BY pg_relation_size(indexrelid) DESC LIMIT 10` — unused indexes (wasted space)
       - `SELECT locked.pid, locked.query, blocking.pid AS blocking_pid, blocking.query AS blocking_query FROM pg_stat_activity locked JOIN pg_locks ON pg_locks.pid = locked.pid WHERE NOT pg_locks.granted LIMIT 5` — lock contention

    2. Analyse and classify:
       - CRITICAL: Queries with mean_exec_time > 5s and > 100 calls
       - WARNING: Tables with seq_scan > 10K and no index on commonly filtered columns
       - INFO: Unused indexes (candidates for removal)
       - INFO: Lock contention patterns

    3. For each slow query, recommend specific indexes using EXPLAIN output.

    4. Report with prioritised recommendations.

    ## Budget
    Max 10 tool calls.

  actions.yaml: |
    actions:
      - name: query-performance-stats
        tool: sql.query
        tier: read
        description: "Query performance statistics and diagnostics"
