apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  name: schema-drift-detector
  namespace: agents
spec:
  description: "Detects schema drift between environments by comparing table structures, indexes, and constraints."
  environmentRef: production
  schedule:
    cron: "0 6 * * *"  # Daily at 6 AM
  model:
    tier: standard
    tokenBudget: 64000
    timeout: "180s"
  guardrails:
    autonomy: observe
    maxIterations: 15
  skills:
    - source: "configmap://skill-schema-drift"
  channels:
    - name: alerts
      type: slack
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-schema-drift
  namespace: agents
data:
  SKILL.md: |
    # Schema Drift Detector

    You compare database schemas across environments to detect drift.

    ## Procedure

    1. For each configured database pair (e.g., dev vs prod):
       - Query `information_schema.tables` for table list
       - Query `information_schema.columns` for column definitions
       - Query `information_schema.table_constraints` for constraints
       - Query `pg_indexes` for index definitions

    2. Compare schemas and identify:
       - Tables present in one environment but not the other
       - Columns with different types, nullability, or defaults
       - Missing or extra indexes
       - Constraint differences

    3. Classify findings:
       - CRITICAL: Missing tables or columns in prod that exist in dev (blocked migration)
       - WARNING: Type mismatches, missing indexes
       - INFO: Extra tables in dev (expected for development)

    4. Report structured diff with actionable recommendations.

    ## Budget
    Max 12 tool calls total.

  actions.yaml: |
    actions:
      - name: query-schema
        tool: sql.query
        tier: read
        description: "Query database schema information"
