apiVersion: legator.io/v1alpha1
kind: LegatorEnvironment
metadata:
  name: aws-production
spec:
  description: "Production AWS account (eu-west-1)"
  cluster:
    name: aws-prod
  credentials:
    aws-credentials:
      type: aws
      source: vault-kv
      path: secret/data/aws/production
    # Or use IRSA:
    # aws-credentials:
    #   type: aws
    #   source: irsa
    #   roleArn: arn:aws:iam::123456789012:role/legator-readonly
  endpoints:
    cloudwatch:
      url: https://monitoring.eu-west-1.amazonaws.com
    cost-explorer:
      url: https://ce.us-east-1.amazonaws.com
  tools:
    - aws.cli
    - dns.query
